// Code generated by MockGen. DO NOT EDIT.
// Source: profiledb.go
//
// Generated by this command:
//
//	mockgen -source profiledb.go -destination profiledb_mock.go -package blockprofile
//

// Package blockprofile is a generated GoMock package.
package blockprofile

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIProfileDB is a mock of IProfileDB interface.
type MockIProfileDB struct {
	ctrl     *gomock.Controller
	recorder *MockIProfileDBMockRecorder
	isgomock struct{}
}

// MockIProfileDBMockRecorder is the mock recorder for MockIProfileDB.
type MockIProfileDBMockRecorder struct {
	mock *MockIProfileDB
}

// NewMockIProfileDB creates a new mock instance.
func NewMockIProfileDB(ctrl *gomock.Controller) *MockIProfileDB {
	mock := &MockIProfileDB{ctrl: ctrl}
	mock.recorder = &MockIProfileDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProfileDB) EXPECT() *MockIProfileDBMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIProfileDB) Add(data ProfileData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockIProfileDBMockRecorder) Add(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIProfileDB)(nil).Add), data)
}

// Close mocks base method.
func (m *MockIProfileDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIProfileDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIProfileDB)(nil).Close))
}

// DeleteByBlockRange mocks base method.
func (m *MockIProfileDB) DeleteByBlockRange(firstBlock, lastBlock uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByBlockRange", firstBlock, lastBlock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByBlockRange indicates an expected call of DeleteByBlockRange.
func (mr *MockIProfileDBMockRecorder) DeleteByBlockRange(firstBlock, lastBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByBlockRange", reflect.TypeOf((*MockIProfileDB)(nil).DeleteByBlockRange), firstBlock, lastBlock)
}

// Flush mocks base method.
func (m *MockIProfileDB) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockIProfileDBMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockIProfileDB)(nil).Flush))
}
