
# Codecov configuration for Aida
#
# This config uses Codecov components to set patch coverage requirements for different parts of the codebase.
# - Files in cmd/ (component: cmd) require at least 70% patch coverage.
# - All other files (component: core) require at least 80% patch coverage.
# - No project-wide coverage checks are enforced, only per-component patch checks.
#
# If a file matches a component, that component's patch rule applies. If not, the global default applies (see below).
#
# Coverage color range:
#   - 0-50: red
#   - 50-80: yellow
#   - 80-100: green
coverage:
  range: 50..80
  round: down
  precision: 2
  status:
    patch:
      default:
        target: auto
  components:
    cmd:
      name: Command Line Tools
      paths:
        - "cmd/"
      status:
        patch:
          target: 70%
    core:
      name: Core
      paths:
        - "!cmd/"
      status:
        patch:
          target: 80%

ignore:
  - "sonic/"
  - "carmen/"
  - "tosca/"
  - "scripts/"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.pb.go"
  - "ethtest/mock_data.go"