# codecov.yaml file contains coverage configurations.
# coverage range
#     - 0-50 is consider red
#     - 50-80 is consider yellow
#     - 80-100 is consider green
# The target coverage of the changes is 80% and threshold is 0% for critical files

coverage:
  range: 50..80
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 80% # target coverage of the changes
        threshold: 1% # allow the coverage to drop by <threshold>%

ignore:
  - "sonic/"
  - "carmen/"
  - "tosca/"
  - "scripts/"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.pb.go"
