// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -source context.go -destination context_mock.go -package tracer
//

// Package tracer is a generated GoMock package.
package tracer

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockContext) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockContextMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockContext)(nil).Close))
}

// WriteAddressOp mocks base method.
func (m *MockContext) WriteAddressOp(op uint8, address *common.Address, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAddressOp", op, address, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAddressOp indicates an expected call of WriteAddressOp.
func (mr *MockContextMockRecorder) WriteAddressOp(op, address, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAddressOp", reflect.TypeOf((*MockContext)(nil).WriteAddressOp), op, address, data)
}

// WriteKeyOp mocks base method.
func (m *MockContext) WriteKeyOp(op uint8, address *common.Address, key *common.Hash, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteKeyOp", op, address, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteKeyOp indicates an expected call of WriteKeyOp.
func (mr *MockContextMockRecorder) WriteKeyOp(op, address, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteKeyOp", reflect.TypeOf((*MockContext)(nil).WriteKeyOp), op, address, key, data)
}

// WriteOp mocks base method.
func (m *MockContext) WriteOp(op uint8, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOp", op, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOp indicates an expected call of WriteOp.
func (mr *MockContextMockRecorder) WriteOp(op, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOp", reflect.TypeOf((*MockContext)(nil).WriteOp), op, data)
}

// WriteValueOp mocks base method.
func (m *MockContext) WriteValueOp(op uint8, address *common.Address, key, value *common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteValueOp", op, address, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteValueOp indicates an expected call of WriteValueOp.
func (mr *MockContextMockRecorder) WriteValueOp(op, address, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteValueOp", reflect.TypeOf((*MockContext)(nil).WriteValueOp), op, address, key, value)
}

// MockByter is a mock of Byter interface.
type MockByter struct {
	ctrl     *gomock.Controller
	recorder *MockByterMockRecorder
	isgomock struct{}
}

// MockByterMockRecorder is the mock recorder for MockByter.
type MockByterMockRecorder struct {
	mock *MockByter
}

// NewMockByter creates a new mock instance.
func NewMockByter(ctrl *gomock.Controller) *MockByter {
	mock := &MockByter{ctrl: ctrl}
	mock.recorder = &MockByterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockByter) EXPECT() *MockByterMockRecorder {
	return m.recorder
}

// Bytes mocks base method.
func (m *MockByter) Bytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes.
func (mr *MockByterMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockByter)(nil).Bytes))
}
