// Code generated by MockGen. DO NOT EDIT.
// Source: file_handler.go
//
// Generated by this command:
//
//	mockgen -source file_handler.go -destination file_handler_mock.go -package tracer
//

// Package tracer is a generated GoMock package.
package tracer

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileHandler is a mock of FileHandler interface.
type MockFileHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFileHandlerMockRecorder
	isgomock struct{}
}

// MockFileHandlerMockRecorder is the mock recorder for MockFileHandler.
type MockFileHandlerMockRecorder struct {
	mock *MockFileHandler
}

// NewMockFileHandler creates a new mock instance.
func NewMockFileHandler(ctrl *gomock.Controller) *MockFileHandler {
	mock := &MockFileHandler{ctrl: ctrl}
	mock.recorder = &MockFileHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileHandler) EXPECT() *MockFileHandlerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFileHandler) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileHandlerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileHandler)(nil).Close))
}

// WriteData mocks base method.
func (m *MockFileHandler) WriteData(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteData", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteData indicates an expected call of WriteData.
func (mr *MockFileHandlerMockRecorder) WriteData(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteData", reflect.TypeOf((*MockFileHandler)(nil).WriteData), data)
}

// WriteUint16 mocks base method.
func (m *MockFileHandler) WriteUint16(data uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteUint16", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteUint16 indicates an expected call of WriteUint16.
func (mr *MockFileHandlerMockRecorder) WriteUint16(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteUint16", reflect.TypeOf((*MockFileHandler)(nil).WriteUint16), data)
}

// WriteUint8 mocks base method.
func (m *MockFileHandler) WriteUint8(idx uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteUint8", idx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteUint8 indicates an expected call of WriteUint8.
func (mr *MockFileHandlerMockRecorder) WriteUint8(idx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteUint8", reflect.TypeOf((*MockFileHandler)(nil).WriteUint8), idx)
}

// MockBuffer is a mock of Buffer interface.
type MockBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockBufferMockRecorder
	isgomock struct{}
}

// MockBufferMockRecorder is the mock recorder for MockBuffer.
type MockBufferMockRecorder struct {
	mock *MockBuffer
}

// NewMockBuffer creates a new mock instance.
func NewMockBuffer(ctrl *gomock.Controller) *MockBuffer {
	mock := &MockBuffer{ctrl: ctrl}
	mock.recorder = &MockBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuffer) EXPECT() *MockBufferMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockBuffer) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockBufferMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockBuffer)(nil).Flush))
}

// Write mocks base method.
func (m *MockBuffer) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockBufferMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockBuffer)(nil).Write), p)
}

// WriteByte mocks base method.
func (m *MockBuffer) WriteByte(c byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteByte", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteByte indicates an expected call of WriteByte.
func (mr *MockBufferMockRecorder) WriteByte(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteByte", reflect.TypeOf((*MockBuffer)(nil).WriteByte), c)
}
