// Code generated by MockGen. DO NOT EDIT.
// Source: file_reader.go
//
// Generated by this command:
//
//	mockgen -source file_reader.go -destination file_reader_mock.go -package tracer
//

// Package tracer is a generated GoMock package.
package tracer

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileReader is a mock of FileReader interface.
type MockFileReader struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderMockRecorder
	isgomock struct{}
}

// MockFileReaderMockRecorder is the mock recorder for MockFileReader.
type MockFileReaderMockRecorder struct {
	mock *MockFileReader
}

// NewMockFileReader creates a new mock instance.
func NewMockFileReader(ctrl *gomock.Controller) *MockFileReader {
	mock := &MockFileReader{ctrl: ctrl}
	mock.recorder = &MockFileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileReader) EXPECT() *MockFileReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFileReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileReader)(nil).Close))
}

// ReadData mocks base method.
func (m *MockFileReader) ReadData(size int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadData", size)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadData indicates an expected call of ReadData.
func (mr *MockFileReaderMockRecorder) ReadData(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadData", reflect.TypeOf((*MockFileReader)(nil).ReadData), size)
}

// ReadUint16 mocks base method.
func (m *MockFileReader) ReadUint16() (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUint16")
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUint16 indicates an expected call of ReadUint16.
func (mr *MockFileReaderMockRecorder) ReadUint16() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUint16", reflect.TypeOf((*MockFileReader)(nil).ReadUint16))
}

// ReadUint8 mocks base method.
func (m *MockFileReader) ReadUint8() (uint8, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUint8")
	ret0, _ := ret[0].(uint8)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUint8 indicates an expected call of ReadUint8.
func (mr *MockFileReaderMockRecorder) ReadUint8() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUint8", reflect.TypeOf((*MockFileReader)(nil).ReadUint8))
}

// MockReadBuffer is a mock of ReadBuffer interface.
type MockReadBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockReadBufferMockRecorder
	isgomock struct{}
}

// MockReadBufferMockRecorder is the mock recorder for MockReadBuffer.
type MockReadBufferMockRecorder struct {
	mock *MockReadBuffer
}

// NewMockReadBuffer creates a new mock instance.
func NewMockReadBuffer(ctrl *gomock.Controller) *MockReadBuffer {
	mock := &MockReadBuffer{ctrl: ctrl}
	mock.recorder = &MockReadBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadBuffer) EXPECT() *MockReadBufferMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReadBuffer) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadBufferMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadBuffer)(nil).Read), p)
}

// ReadByte mocks base method.
func (m *MockReadBuffer) ReadByte() (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByte")
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByte indicates an expected call of ReadByte.
func (mr *MockReadBufferMockRecorder) ReadByte() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByte", reflect.TypeOf((*MockReadBuffer)(nil).ReadByte))
}
