// Code generated by MockGen. DO NOT EDIT.
// Source: db_search.go
//
// Generated by this command:
//
//	mockgen -source db_search.go -destination db_search_mock.go -package utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	ethdb "github.com/ethereum/go-ethereum/ethdb"
	gomock "go.uber.org/mock/gomock"
)

// MockethDatabase is a mock of ethDatabase interface.
type MockethDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockethDatabaseMockRecorder
	isgomock struct{}
}

// MockethDatabaseMockRecorder is the mock recorder for MockethDatabase.
type MockethDatabaseMockRecorder struct {
	mock *MockethDatabase
}

// NewMockethDatabase creates a new mock instance.
func NewMockethDatabase(ctrl *gomock.Controller) *MockethDatabase {
	mock := &MockethDatabase{ctrl: ctrl}
	mock.recorder = &MockethDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockethDatabase) EXPECT() *MockethDatabaseMockRecorder {
	return m.recorder
}

// Ancient mocks base method.
func (m *MockethDatabase) Ancient(kind string, number uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ancient", kind, number)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ancient indicates an expected call of Ancient.
func (mr *MockethDatabaseMockRecorder) Ancient(kind, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ancient", reflect.TypeOf((*MockethDatabase)(nil).Ancient), kind, number)
}

// AncientDatadir mocks base method.
func (m *MockethDatabase) AncientDatadir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AncientDatadir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AncientDatadir indicates an expected call of AncientDatadir.
func (mr *MockethDatabaseMockRecorder) AncientDatadir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AncientDatadir", reflect.TypeOf((*MockethDatabase)(nil).AncientDatadir))
}

// AncientRange mocks base method.
func (m *MockethDatabase) AncientRange(kind string, start, count, maxBytes uint64) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AncientRange", kind, start, count, maxBytes)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AncientRange indicates an expected call of AncientRange.
func (mr *MockethDatabaseMockRecorder) AncientRange(kind, start, count, maxBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AncientRange", reflect.TypeOf((*MockethDatabase)(nil).AncientRange), kind, start, count, maxBytes)
}

// AncientSize mocks base method.
func (m *MockethDatabase) AncientSize(kind string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AncientSize", kind)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AncientSize indicates an expected call of AncientSize.
func (mr *MockethDatabaseMockRecorder) AncientSize(kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AncientSize", reflect.TypeOf((*MockethDatabase)(nil).AncientSize), kind)
}

// Ancients mocks base method.
func (m *MockethDatabase) Ancients() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ancients")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ancients indicates an expected call of Ancients.
func (mr *MockethDatabaseMockRecorder) Ancients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ancients", reflect.TypeOf((*MockethDatabase)(nil).Ancients))
}

// Close mocks base method.
func (m *MockethDatabase) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockethDatabaseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockethDatabase)(nil).Close))
}

// Compact mocks base method.
func (m *MockethDatabase) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockethDatabaseMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockethDatabase)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockethDatabase) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockethDatabaseMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockethDatabase)(nil).Delete), key)
}

// DeleteRange mocks base method.
func (m *MockethDatabase) DeleteRange(start, end []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRange", start, end)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRange indicates an expected call of DeleteRange.
func (mr *MockethDatabaseMockRecorder) DeleteRange(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRange", reflect.TypeOf((*MockethDatabase)(nil).DeleteRange), start, end)
}

// Get mocks base method.
func (m *MockethDatabase) Get(key []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockethDatabaseMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockethDatabase)(nil).Get), key)
}

// Has mocks base method.
func (m *MockethDatabase) Has(key []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockethDatabaseMockRecorder) Has(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockethDatabase)(nil).Has), key)
}

// HasAncient mocks base method.
func (m *MockethDatabase) HasAncient(kind string, number uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAncient", kind, number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAncient indicates an expected call of HasAncient.
func (mr *MockethDatabaseMockRecorder) HasAncient(kind, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAncient", reflect.TypeOf((*MockethDatabase)(nil).HasAncient), kind, number)
}

// ModifyAncients mocks base method.
func (m *MockethDatabase) ModifyAncients(arg0 func(ethdb.AncientWriteOp) error) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyAncients", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyAncients indicates an expected call of ModifyAncients.
func (mr *MockethDatabaseMockRecorder) ModifyAncients(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyAncients", reflect.TypeOf((*MockethDatabase)(nil).ModifyAncients), arg0)
}

// NewBatch mocks base method.
func (m *MockethDatabase) NewBatch() ethdb.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(ethdb.Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockethDatabaseMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockethDatabase)(nil).NewBatch))
}

// NewBatchWithSize mocks base method.
func (m *MockethDatabase) NewBatchWithSize(size int) ethdb.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatchWithSize", size)
	ret0, _ := ret[0].(ethdb.Batch)
	return ret0
}

// NewBatchWithSize indicates an expected call of NewBatchWithSize.
func (mr *MockethDatabaseMockRecorder) NewBatchWithSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatchWithSize", reflect.TypeOf((*MockethDatabase)(nil).NewBatchWithSize), size)
}

// NewIterator mocks base method.
func (m *MockethDatabase) NewIterator(prefix, start []byte) ethdb.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(ethdb.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockethDatabaseMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockethDatabase)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockethDatabase) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockethDatabaseMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockethDatabase)(nil).Put), key, value)
}

// ReadAncients mocks base method.
func (m *MockethDatabase) ReadAncients(fn func(ethdb.AncientReaderOp) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAncients", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadAncients indicates an expected call of ReadAncients.
func (mr *MockethDatabaseMockRecorder) ReadAncients(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAncients", reflect.TypeOf((*MockethDatabase)(nil).ReadAncients), fn)
}

// Stat mocks base method.
func (m *MockethDatabase) Stat() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockethDatabaseMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockethDatabase)(nil).Stat))
}

// Sync mocks base method.
func (m *MockethDatabase) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockethDatabaseMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockethDatabase)(nil).Sync))
}

// Tail mocks base method.
func (m *MockethDatabase) Tail() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tail")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tail indicates an expected call of Tail.
func (mr *MockethDatabaseMockRecorder) Tail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*MockethDatabase)(nil).Tail))
}

// TruncateHead mocks base method.
func (m *MockethDatabase) TruncateHead(n uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateHead", n)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TruncateHead indicates an expected call of TruncateHead.
func (mr *MockethDatabaseMockRecorder) TruncateHead(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateHead", reflect.TypeOf((*MockethDatabase)(nil).TruncateHead), n)
}

// TruncateTail mocks base method.
func (m *MockethDatabase) TruncateTail(n uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateTail", n)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TruncateTail indicates an expected call of TruncateTail.
func (mr *MockethDatabaseMockRecorder) TruncateTail(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateTail", reflect.TypeOf((*MockethDatabase)(nil).TruncateTail), n)
}
