// Code generated by MockGen. DO NOT EDIT.
// Source: hash_provider.go
//
// Generated by this command:
//
//	mockgen -source hash_provider.go -destination hash_provider_mocks.go -package utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockHashProvider is a mock of HashProvider interface.
type MockHashProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHashProviderMockRecorder
	isgomock struct{}
}

// MockHashProviderMockRecorder is the mock recorder for MockHashProvider.
type MockHashProviderMockRecorder struct {
	mock *MockHashProvider
}

// NewMockHashProvider creates a new mock instance.
func NewMockHashProvider(ctrl *gomock.Controller) *MockHashProvider {
	mock := &MockHashProvider{ctrl: ctrl}
	mock.recorder = &MockHashProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashProvider) EXPECT() *MockHashProviderMockRecorder {
	return m.recorder
}

// GetBlockHash mocks base method.
func (m *MockHashProvider) GetBlockHash(blockNumber int) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", blockNumber)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockHashProviderMockRecorder) GetBlockHash(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockHashProvider)(nil).GetBlockHash), blockNumber)
}

// GetStateRootHash mocks base method.
func (m *MockHashProvider) GetStateRootHash(blockNumber int) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateRootHash", blockNumber)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateRootHash indicates an expected call of GetStateRootHash.
func (mr *MockHashProviderMockRecorder) GetStateRootHash(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateRootHash", reflect.TypeOf((*MockHashProvider)(nil).GetStateRootHash), blockNumber)
}
